// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionHelper: typeof import('./src/components/helper/ActionHelper.vue')['default']
    Code: typeof import('./src/components/message/Code.vue')['default']
    CodeEditor: typeof import('./src/components/CodeEditor.vue')['default']
    Container: typeof import('./src/components/message/Container.vue')['default']
    DragBox: typeof import('./src/components/helper/DragBox.vue')['default']
    DragHelper: typeof import('./src/components/DragHelper.vue')['default']
    DropDown: typeof import('./src/components/helper/DropDown.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    Fgs: typeof import('./src/components/helper/action/fgs.vue')['default']
    Load: typeof import('./src/components/message/Load.vue')['default']
    OffsetHelper: typeof import('./src/components/helper/OffsetHelper.vue')['default']
    PageAdmin: typeof import('./src/components/helper/PageAdmin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Service: typeof import('./src/components/message/Service.vue')['default']
    SizeControl: typeof import('./src/components/helper/style/SizeControl.vue')['default']
    StyleControl: typeof import('./src/components/helper/StyleControl.vue')['default']
    StyleHelper: typeof import('./src/components/StyleHelper.vue')['default']
    UnoClass: typeof import('./src/components/helper/style/UnoClass.vue')['default']
  }
}
