/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/widgets/Button.vue')['default']
    Cascader: typeof import('./src/widgets/Cascader.vue')['default']
    Checkbox: typeof import('./src/widgets/Checkbox.vue')['default']
    CheckboxGroup: typeof import('./src/widgets/CheckboxGroup.vue')['default']
    Container: typeof import('./src/modals/Container.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTree: typeof import('element-plus/es')['ElTree']
    FormConf: typeof import('./src/components/FormConf.vue')['default']
    Input: typeof import('./src/widgets/Input.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    PaneForm: typeof import('./src/components/PaneForm.vue')['default']
    Property: typeof import('./src/zones/Property.vue')['default']
    Route: typeof import('./src/components/Route.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/widgets/Select.vue')['default']
    Tree: typeof import('./src/zones/Tree.vue')['default']
  }
}
