export enum ALIOTH_EVENT {
  CREATE_BLOCK = 'CREATE_BLOCK',
  APPEND_NODE = 'APPEND_NODE',
  INSERT_BLOCK = 'INSERT_BLOCK',
  REMOVE_NODE = 'REMOVE_BLOCK',
  PROPERTY_CHANGE = 'PROPERTY_CHANGE',
  REDO = 'REDO',
  UNDO = 'UNDO',
}
