/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionHelper: typeof import('./src/components/wrappers/ActionHelper.vue')['default']
    Container: typeof import('./src/components/modals/Container.vue')['default']
    Dialog: typeof import('./src/components/base/Dialog.vue')['default']
    DragBox: typeof import('./src/components/wrappers/DragBox.vue')['default']
    DragHelper: typeof import('./src/components/base/DragHelper.vue')['default']
    Editable: typeof import('./src/components/base/Editable.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTree: typeof import('element-plus/es')['ElTree']
    FormConf: typeof import('./src/components/base/FormConf.vue')['default']
    OffsetHelper: typeof import('./src/components/wrappers/OffsetHelper.vue')['default']
    PaneForm: typeof import('./src/components/panes/PaneForm.vue')['default']
    Radio: typeof import('./src/components/base/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/base/Select.vue')['default']
    TabInput: typeof import('./src/components/base/TabInput.vue')['default']
    Tooltip: typeof import('./src/components/base/Tooltip.vue')['default']
  }
}
